# Configurações do Codecov
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
    changes: no

# Configurações de comentários
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

# Configurações de ignorar arquivos
ignore:
  - "tests/**/*"
  - "vendor/**/*"
  - "storage/**/*"
  - "bootstrap/**/*"
  - "config/**/*"
  - "database/**/*"
  - "resources/**/*"
  - "routes/**/*"
  - "public/**/*"
  - "*.js"
  - "*.css"
  - "*.html"

# Configurações de relatórios
reports:
  - name: "Cobertura de Código"
    path: "build/coverage/index.html"
    format: html
  - name: "Relatório de Testes"
    path: "build/report.junit.xml"
    format: junit

# Configurações de notificações
notify:
  require_ci_to_pass: yes
  wait_for_ci: yes

# Configurações de cache
cache:
  after_n_builds: 3

# Configurações de branches
branches:
  - main
  - develop
  - feature/*
  - bugfix/*
  - hotfix/*

# Configurações de ambiente
environment:
  - CI
  - PHP_VERSION
  - WORDPRESS_VERSION
  - DOCKER_VERSION

# Configurações de timeout
timeout: 300

# Configurações de retry
retry:
  max_retries: 3
  delay: 5

# Configurações de debug
debug:
  verbose: false
  quiet: false 